# SPDX-License-Identifier: MIT-0
---
  # Устанавливаем postgresql14-server
- name: Install postgresql-server 14
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present
    update_cache: true

# Запускаем postgresql-14
- name: Enable and start service
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true
