---

- name: Apply global read lock
  community.mysql.mysql_query:
    login_user: "{{ nextcloud_user }}"
    login_password: "{{ nextcloud_password }}"
    query: "FLUSH TABLES WITH READ LOCK;"
  delegate_to: "{{ inventory_hostname }}"


- name: Run RESET MASTER command which will delete all existing binary log files and reset the binary log index file on the primary
  become: true
  community.mysql.mysql_replication:
    mode: resetprimary
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Dump multiple databases
  become: true
  community.mysql.mysql_db:
    state: dump
    name: all
    target: "{{ backup_dir }}/{{ inventory_hostname }}/{{ dumpfile_name }}"    
    master_data: 2
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Apply global read lock
  community.mysql.mysql_query:
    login_user: "{{ nextcloud_user }}"
    login_password: "{{ nextcloud_password }}"
    query: UNLOCK TABLES;
  delegate_to: "{{ inventory_hostname }}"
