---
- name: Run RESET MASTER command which will delete all existing binary log files and reset the binary log index file on the primary
  become: true
  community.mysql.mysql_replication:
    mode: resetprimary
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Dump multiple databases
  become: true
  community.mysql.mysql_db:
    state: dump
    name: all
    target: "{{ backup_dir }}/{{ inventory_hostname }}/mysqldump_{{ inventory_hostname }}_{{ ansible_date_time.date }}.sql"
    master_data: 2
 #    primary_auto_position: false
    login_unix_socket: /var/run/mysqld/mysqld.sock
