---
network:
  version: 2
  renderer: networkd
  ethernets:
    ens6:
      addresses:
      - 192.168.255.6/30
      routes:
        - to: 192.168.255.8/30
          via: 192.168.255.5

        - to: 192.168.2.0/24
          via: 192.168.255.5

        - to: 192.168.0.0/28
          via: 192.168.255.5

        - to: default
          via: 192.168.255.5

    ens7:
      addresses:
      - 192.168.1.1/25
    ens8:
      addresses:
      - 192.168.1.129/26
    ens9:
      addresses:
      - 192.168.1.193/26
    ens10:
      addresses:
      - 192.168.50.30/24





