Vagrant.configure("2") do |config|
  # Base VM OS configuration.
  config.vm.box = "ubuntu/jammy64"
  config.vm.provider :libvirt do |v|
    v.memory = 2048
    v.cpus = 2
  end

  # Define two VMs with static private IP addresses.
  boxes = [
    { :name => "27client",
      :ip => "192.168.11.150",
    },
    { :name => "27backup",
      :ip => "192.168.11.160",
    }
  ]
  # Provision each of the VMs.
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip], libvirt__intnet: "dns"
      if opts[:name] == boxes.last[:name] 
        config.vm.provision "ansible" do |ansible|
          ansible.playbook = "ansible/provision.yml"
          ansible.inventory_path = "ansible/hosts"
          ansible.host_key_checking = "false"
          ansible.limit = "all"
        end
      end
      
    end
  end
end