# SPDX-License-Identifier: MIT-0
---
# handlers file for setup_node_exporter
- name: "Start node_exporter"
  ansible.builtin.service:
    name: node_exporter
    state: started
    enabled: true

- name: "Restart node_exporter"
  ansible.builtin.service:
    name: node_exporter
    state: restarted
    daemon_reload: true
