---
- name: Register Elasticsearch snapshot repository
  community.elastic.elastic_snapshot_repository:
    name: "{{ elasticsearch_repo_name }}"
    state: present
    type: fs
#    settings:
    location: "{{ elasticsearch_repo }}" # Path accessible by all master and data nodes
    login_hosts: "{{ elasticsearch_host }}"
    login_port: "{{ elasticsearch_port }}"
    login_user: "{{ elastic_user }}"
    login_password: "{{ elastic_password }}"

    # Add authentication details if required
