---
- name: Install a elasticsearch-8.9.1-amd64 package
  ansible.builtin.apt:
    deb: "{{ distrib_path }}/elk-8.9-deb/elasticsearch-{{ elk_version }}-amd64.deb"
    state: present
  tags: install

- name: Set up elasticsearch server
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: "0644"
    owner: root
  tags: setup

- name: Set up jvm
  ansible.builtin.template:
    src: elasticsearch_jvm.option.j2
    dest: /etc/elasticsearch/jvm.options.d/jvm.options
    mode: "0644"
    owner: root
  tags: setup

- name: Restart elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch
    daemon-reload: true
    state: restarted
    enabled: true
  tags: restart
