---
- name: OSPF
 # Указываем имя хоста или группу, которые будем настраивать
  hosts: all
 # Параметр выполнения модулей от root-пользователя
  become: true
 # Указание файла с дополнительными переменными (понадобится при добавлении темплейтов)
  vars_files:
    - defaults/main.yml
  tasks:
  # Обновление пакетов и установка traceroute, net-tools mc
    - name: Install base tools
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - traceroute
        - net-tools
        - mc
#        - vim
#        - tcpdump
    # Отключаем UFW и удаляем его из автозагрузки
    - name: Disable ufw service
      ansible.builtin.service:
        name: ufw
        state: stopped
        enabled: false

    # Добавляем gpg-key репозитория
    - name: Add gpg frrouting.org
      ansible.builtin.apt_key:
        url: "https://deb.frrouting.org/frr/keys.asc"
        state: present

    # Добавляем репозиторий https://deb.frrouting.org/frr
    - name: Add frr repo
      ansible.builtin.apt_repository:
        repo: 'deb https://deb.frrouting.org/frr {{ ansible_distribution_release }} frr-stable'
        state: present

    #  Обновляем пакеты и устанавливаем FRR
    - name: Install FRR packages
      ansible.builtin.apt:
        name:
          - frr
          - frr-pythontools
        state: present
        update_cache: true

    - name: Disable default route
      ansible.builtin.template:
        src: 50-cloud-init.yaml
        dest: /etc/netplan/50-cloud-init.yaml
        owner: root
        group: root
        mode: "0600"
  #    when: (ansible_hostname != "router1")

    - name: Apply netplan config
      ansible.builtin.command: netplan apply
      become: true
      ignore_errors: true
  #    when: (ansible_hostname != "router1")

    # Включаем маршрутизацию транзитных пакетов
    - name: Set up forward packages across routers
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present

    # Копируем файл daemons на хосты, указываем владельца и права
    - name: Base set up OSPF
      ansible.builtin.template:
        src: daemons
        dest: /etc/frr/daemons
        owner: frr
        group: frr
        mode: "0640"

    # Отключаем запрет ассиметричного роутинга
    - name: Set up asynchronous routing
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: '0'
        state: present

    # Делаем интерфейс enp0s8 в router1 «дорогим»
    - name: Set up OSPF
      ansible.builtin.template:
        src: frr.conf.j2
        dest: /etc/frr/frr.conf
        owner: frr
        group: frr
        mode: "0640"
      tags:
        - setup_ospf

    # Применяем настройки
    - name: restart FRR
      ansible.builtin.service:
        name: frr
        state: restarted
        enabled: true
      tags:
        - setup_ospf

...
