MACHINES = {
  :"pam" => {
        :box_name => "ubuntu/jammy64",
        :cpus => 2,
        :memory => 1024,
        :ip => "192.168.50.100",
    }
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.synced_folder ".", "/vagrant", disabled: true
        config.vm.network "private_network", ip: boxconfig[:ip], libvirt__intnet: "dns"
#        config.vm.network :private_network, ip: boxconfig[:ip], auto_config: "false"
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
#            box.vm.box_version = boxconfig[:box_version]
            box.vm.hostname = boxname.to_s

            box.vm.provider "libvirt" do |v|
                v.memory = boxconfig[:memory]
                v.cpus = boxconfig[:cpus]
            end
            box.vm.provision "shell", inline: <<-SHELL
		#Разрешаем подключение пользователей по SSH с использованием пароля
                sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
                systemctl restart sshd.service
                    SHELL
        end
    end
end
