# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "almalinux/8" #"centos/stream8"
#  config.vm.box_version = "20210210.0"

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 1
  end

  boxes = {
    :'ipa.otus.lan' => { 
      :name => "ipa.otus.lan",
      :ip => "192.168.57.10",
    },
    :'client1.otus.lan' => {
      :name => "client1.otus.lan",
      :ip => "192.168.57.11",
    },
    :'client2.otus.lan' => {
      :name => "client2.otus.lan",
      :ip => "192.168.57.12",
    }
  }

  boxes.each do |boxname, opts|
    config.vm.define boxname do |config|    
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip]
    end
    if opts[:name] == "client2.otus.lan"
      config.vm.provision "ansible" do |ansible|
       ansible.playbook = "ansible/provision.yml"
       ansible.inventory_path = "ansible/hosts"
       ansible.host_key_checking = "false"
       ansible.become = "true"
       ansible.limit = "all"
      end
    end      
  end

end
