---
network:
  version: 2
  renderer: networkd
  ethernets:
    ens6:
      addresses:
      - 192.168.255.10/30
      routes:
        - to: 192.168.255.4/30
          via: 192.168.255.9

        - to: 192.168.1.0/24
          via: 192.168.255.9

        - to: 192.168.0.0/28
          via: 192.168.255.9

        - to: default
          via: 192.168.255.9

    ens7:
      addresses:
      - 192.168.2.1/26
    ens8:
      addresses:
      - 192.168.2.65/26
    ens9:
      addresses:
      - 192.168.2.129/26
    ens10:
      addresses:
      - 192.168.2.193/26
    ens11:
      addresses:
      - 192.168.50.20/24
