---
network:
  version: 2
  renderer: networkd
  ethernets:
    ens6:
      addresses:
      - 192.168.1.2/25
      routes:
      - to: 192.168.255.4/30
        via: 192.168.1.1

      - to: 192.168.0.0/28
        via: 192.168.1.1

      - to: 192.168.255.8/30
        via: 192.168.1.1

      - to: 192.168.2.0/24
        via: 192.168.1.1

      - to: default
        via: 192.168.1.1

    ens7:
      addresses:
      - 192.168.50.31/24

