---
- name: Create dir ssl
  become: true
  ansible.builtin.file:
    path: /etc/ssl/{{ ansible_hostname }}
    state: directory
    mode: '0755'

- name: Check nextcloud cert status
  ansible.builtin.stat:
    path: "{{ ssl_keys_path }}/crt/{{ ansible_hostname }}.loc.crt"
  register: reg_cert_status

- name: Copy nextcloud SSL certificate file
  ansible.builtin.copy:
    src: "{{ ssl_keys_path }}/crt/{{ ansible_hostname }}.loc.crt"
    dest: "/etc/ssl/{{ ansible_hostname }}/{{ ansible_hostname }}.loc.crt"
    mode: '0644'
    owner: root
    group: root
    remote_src: true
  when: reg_cert_status.stat.exists

- name: Copy nextcloud SSL private key file
  ansible.builtin.copy:
    src: "{{ ssl_keys_path }}/private/{{ ansible_hostname }}.loc.key"
    dest: "/etc/ssl/{{ ansible_hostname }}/{{ ansible_hostname }}.loc.key"
    mode: '0644'
    owner: root
    group: root
    remote_src: true
  when: reg_cert_status.stat.exists

- name: Set up nextcloud server
  ansible.builtin.template:
    src: nextcloud_exp.conf.j2
    dest: /etc/nginx/sites-available/nextcloud.conf
    mode: "0644"
    owner: root

- name: Enable nextcloud
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/nextcloud
    src: /etc/nginx/sites-available/nextcloud.conf
    state: link

- name: Disable default nginx path
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
