---
- name: Set nextcloud maintenance mode ON
  become: true
  ansible.builtin.shell:
    cmd: "sudo -E -u www-data php {{ nextcloud_data_dir }}/occ maintenance:mode --on"

- name: Copy nginx config
  ansible.builtin.copy:
    src: /etc/nginx/sites-available/nextcloud.conf
    dest: "{{ nextcloud_backup_dir }}/nextcloud.conf"
    mode: '0644'
    owner: root
    remote_src: true

- name: Create DB dump
#  become: true
  include_tasks:
    file: create_mysql_dump/tasks/create_mysql_dump.yml

- name: Check NC backup dir status
  ansible.builtin.stat:
    path: "{{ nextcloud_backup_dir }}/nextcloud_{{ ansible_date_time.date }}"
  register: reg_nc_backup_status

- name: Check nextcloud dir
  ansible.builtin.debug:
    msg: "{{ reg_nc_backup_status.stat }}"

- name: Archive Nextcloud data directory and config
  become: true
  ansible.builtin.copy:
    src: "{{ nextcloud_data_dir }}"
    dest: "{{ nextcloud_backup_dir }}/nextcloud_{{ ansible_date_time.date }}"
    owner: www-data
    group: www-data
    mode: "0755"
    remote_src: true
  when: not reg_nc_backup_status.stat.exists

- name: Set nextcloud maintenance mode OFF
  become: true
  ansible.builtin.shell:
    cmd: "sudo -E -u www-data php {{ nextcloud_data_dir }}/occ maintenance:mode --off"
