---
- name: Install a filebeat-8.9.1-amd64 package
  ansible.builtin.apt:
    deb: "{{ distrib_path }}/elk-8.9-deb/filebeat-{{ elk_version }}-amd64.deb"
    state: present

- name: Set up filebeat
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    mode: "0644"
    owner: root
  when: (ansible_hostname != "nextcloud")

- name: Set up filebeat
  ansible.builtin.template:
    src: filebeat_tologstash.yml.j2
    dest: /etc/filebeat/filebeat.yml
    mode: "0644"
    owner: root
  when: (ansible_hostname == "nextcloud")

- name: Start filebeat
  ansible.builtin.systemd:
    name: filebeat
    daemon-reload: true
    enabled: true
    state: started
