192.168.56.10
192.168.56.100
192.168.56.15

[otus_web]
web ansible_host=192.168.56.10 ansible_ssh_private_key_file=.vagrant/machines/web/libvirt/private_key

[otus_simple]
simple ansible_host=192.168.56.100 ansible_ssh_private_key_file=.vagrant/machines/simple/libvirt/private_key

[otus_log]
log ansible_host=192.168.56.15 ansible_ssh_private_key_file=.vagrant/machines/log/libvirt/private_key

[otus_all:children]
otus_web
otus_log
otus_simple
