# SPDX-License-Identifier: MIT-0
---
# tasks file for setup_monitoring

- name: Gen ssl certs
  ansible.builtin.import_role:
    name: setup_ssl_certs
  tags: Gen_certs

- name: Gen ssl certs
  vars: 
    ansible_hostname: prometheus
  ansible.builtin.import_role:
    name: setup_ssl_certs
  tags: Gen_certs

- name: Setup Prometheus
  include_tasks: install_prometheus.yml
  tags: Prometheus

- name: Setup Grafana
  include_tasks: install_grafana.yml
  tags: Grafana

- name: Setup Alert_manager
  include_tasks: install_alertmanager.yml
  tags: Alert_manager

- name: Copy prometheus cert
  vars:
    webserver: elk
  include_tasks: copy_certs.yml
  tags: Copy_certs

- name: Copy elk cert
  vars:
    webserver: elk
  include_tasks: copy_certs.yml
  tags: Copy_certs

- name: Install nginx
  include_tasks: install_nginx.yml
  tags: nginx
