---
- name: Check cert status
  ansible.builtin.stat:
    path: "{{ ssl_keys_path }}/crt/{{ ansible_hostname }}.loc.crt"
  register: reg_cert_status

- name: Get cert status info
  ansible.builtin.debug:
    msg: "{{ reg_cert_status.stat.exists }}"
  when: reg_cert_status.stat.exists

- name: Generate an OpenSSL private key
  community.crypto.openssl_privatekey:
    path: "{{ ssl_keys_path }}/private/{{ ansible_hostname }}.loc.key" 
    size: "{{ my_key_size }}"
    type: "{{ my_key_type }}"
    backup: true
  when: not reg_cert_status.stat.exists

- name: Generate an OpenSSL Certificate Signing Request with Subject information
  community.crypto.openssl_csr:
    path: "{{ ssl_keys_path }}/csr/{{ ansible_hostname }}.loc.csr"
    privatekey_path: "{{ ssl_keys_path }}/private/{{ ansible_hostname }}.loc.key"
    country_name: "{{ my_country_name }}"
    organization_name: "{{ my_organization_name }}"
    email_address: "{{ my_email_address }}"
    common_name: "{{ ansible_hostname }}.loc"
  register: csr_result
  when: not reg_cert_status.stat.exists

- name: Print CSR result
  ansible.builtin.debug:
    var: csr_result

- name: Generate an OpenSSL certificate signed with own CA certificate
  ansible.builtin.openssl_certificate:
    path: "{{ ssl_keys_path }}/crt/{{ ansible_hostname }}.loc.crt"
    csr_path: "{{ ssl_keys_path }}/csr/{{ ansible_hostname }}.loc.csr"
    ownca_path: "{{ ssl_keys_path }}/crt/rootCA.pem"
    ownca_privatekey_path: "{{ ssl_keys_path }}/private/rootCA.key"
    provider: ownca
  register: reg_crt
  when: not reg_cert_status.stat.exists

- name: Get certificate info
  ansible.builtin.openssl_certificate_info:
    path: "{{ ssl_keys_path }}/crt/{{ ansible_hostname }}.loc.crt"
  register: reg_crt_info

- name: Print certificate info
  ansible.builtin.debug:
    var: reg_crt_info
