---
- name: Postgres
  hosts: all
  become: true
  tasks:
# Устанавливаем vim и telnet (для более удобной работы с хостами)
    - name: Install base tools
      ansible.builtin.apt:
        name:
          - vim
          - telnet
          - mc
        state: present
        update_cache: true

# Запуск ролей install_postgres и postgres_replication на хостах node1 и node2
- name: Install postgres 14 and set up replication
  hosts: node1,node2
  become: true
  roles:
    - install_postgres
    - postgres_replication

# Запуск роли install_barman на всех хостах
- name: Set up backup
  hosts: all
  become: true
  roles:
    - install_barman
