---
- name: Restore server
  become: true
  vars:
    restore_hostname: "elk"
    restore_host_ip: "{{ hostvars['elk']['ansible_host'] }}"
  hosts: servicenode
  vars_files:
    - ./vars/variables.yml
  roles:
    - setup_restore_node

- name: Install ELK
  hosts: servicenode
  become: true
  vars_files:
    - ./vars/variables.yml
  roles:
    - setup_elk
