---
- name: backup monitoring
  hosts: monitor
  become: true
  vars_files:
    - ./vars/variables.yml
  tasks:
    - name: Import monitor backups task
      include_tasks:
        file: setup_monitoring/tasks/monitoring_backup.yml
