---
- name: Install node_exporter
  hosts: mysqlrepl
  become: true
  vars_files:
    - ./vars/variables.yml
  roles:
    - setup_node_exporter

- name: Install file_beat
  hosts: mysqlrepl
  become: true
  vars_files:
    - ./vars/variables.yml
  roles:
    - setup_beats

- name: MYSQL-server
  hosts: mysqlrepl
  become: true
  vars_files:
    - ./vars/variables.yml
  roles:
    - install_mysql

- name: Create NEXTCLOUD MySQL-DUMP
  hosts: "{{ mysql_source_hostname }}"
  vars:
    source_hostname: "{{ mysql_source_hostname }}"
    dumpfile_name: "mysqldump_{{ mysql_source_hostname }}_{{ ansible_date_time.date }}_hot.sql"
  vars_files:
    - ./vars/variables.yml
  roles:
    - create_mysql_dump

- name: Setup MySQL-REPLICA
  hosts: mysqlrepl
  vars:
    source_hostname: "{{ mysql_source_hostname }}"
    dumpfile_name: "mysqldump_{{ mysql_source_hostname }}_{{ ansible_date_time.date }}_hot.sql"
  become: true
  vars_files:
    - ./vars/variables.yml
  roles:
    - setup_replica
