---

- name: MYSQL-server
  hosts: mysqlrepl
  become: true
  vars_files:
    - ./vars/variables.yml
  roles:
    - install_mysql

- name: Create NEXTCLOUD MySQL-DUMP
  hosts: "{{ mysql_source_hostname }}"
#  become: true
  vars:
    ansible_host_key_checking: false
  vars_files:
    - ./vars/variables.yml
  roles:
    - create_mysql_dump

- name: Setup MySQL-REPLICA
  hosts: mysqlrepl
  vars:
    source_hostname: "{{ mysql_source_hostname }}"
  become: true
  vars_files:
    - ./vars/variables.yml
  roles:
    - setup_replica

- name: Install node_exporter
  hosts: mysqlrepl
  become: true
  vars_files:
    - ./vars/variables.yml
  roles:
    - setup_node_exporter
