---
- name: backup Nextcloud
  hosts: nextcloud
  become: true
  vars:
    dumpfile_name: "mysqldump_{{ inventory_hostname }}_{{ ansible_date_time.date }}.sql"
  vars_files:
    - ./vars/variables.yml
  tasks:
    - name: Import nextcloud backups task
      include_tasks:
        file: install_nextcloud/tasks/nextcloud_backup.yml
