---
- name: Restore server
  become: true
  vars:
    restore_hostname: "monitor"
    restore_host_ip: "{{ hostvars['monitor']['ansible_host'] }}"
  hosts: servicenode
  vars_files:
    - ./vars/variables.yml
  roles:
    - setup_restore_node

- name: Install monitoring server
  hosts: servicenode
  become: true
  vars_files:
    - ./vars/variables.yml
  roles:
    - setup_monitoring
