---
- name: Explore hostvars
  hosts: monitor
  gather_facts: false
  vars_files:
    - ./vars/variables.yml
  tasks:
    # - name: Display host variables for the current host
    #   debug:
    #     msg: "Host: {{ inventory_hostname }} has the following variables: {{ hostvars[inventory_hostname] }}"

    # - name: Display a specific variable for the current host
    #   debug:
    #     msg: "Host {{ inventory_hostname }} has environment: {{ hostvars[inventory_hostname]['ansible_host'] }}"


    # - name: Get certificate info
    #   ansible.builtin.openssl_certificate_info:
    #     path: "{{ ssl_keys_path }}/crt/{{ ansible_hostname }}.loc.crt" # /etc/ssl/crt/ansible.com.crt
    #     # for valid_at, invalid_at and valid_in
    #     # valid_at:
    #     #   one_day_ten_hours: "+1d10h"
    #     #   fixed_timestamp: 20200331202428Z
    #     #   ten_seconds: "+10"
    #   register: reg_crt_info

    # - name: Print certificate info
    #   ansible.builtin.debug:
    #     var: reg_crt_info
    - name: Print certificate info
      ansible.builtin.debug:
        msg: mysqldump_{{ ansible_date_time.date }}  # `date +\"%Y%m%d\"`.sql
