# -*- mode: ruby -*-
# vi: set ft=ruby :
# 
ENV['VAGRANT_DEFAULT_PROVIDER'] = "virtualbox"
$global_box_name="ubuntu/jammy64" 

MACHINES = {
  :ns01 => {
        :box_name => $global_box_name,
        :vm_name => "ns01",
        :net => [
                   ['192.168.56.10',  5, "255.255.255.0", "dns"],
                ]
  },
  :ns02 => {
        :box_name => $global_box_name,
        :vm_name => "ns02",
        :net => [
                   ['192.168.56.11',  5, "255.255.255.0", "dns"],
                ]
  },
  :client => {
        :box_name => $global_box_name,
        :vm_name => "client",
        :net => [
                  ['192.168.56.15',  5, "255.255.255.0", "dns"],
                ]
  },
  :client2 => {
        :box_name => $global_box_name,
        :vm_name => "client2",
        :net => [
                  ['192.168.56.16',  5, "255.255.255.0", "dns"],
                ]
  },  
}

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
	  v.memory = 1024
  end
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.hostname = boxconfig[:vm_name]
      boxconfig[:net].each do |ipconf|
        box.vm.network("private_network" \
                    , ip: ipconf[0] \
                    , virtualbox__netmask: ipconf[2] \
                    #, virtualbox__intnet: ipconf[3] \
                    )        
      end
      if boxconfig[:vm_name] == "client2"
        box.vm.provision "ansible" do |ansible|
#          ansible.verbose = "vvv"
          ansible.playbook = "ansible/playbook.yml"
          ansible.inventory_path = "ansible/hosts"
#          ansible.host_key_checking = "false"
          ansible.limit = "all"
        end
      end    
    end
  end
end

