---
- name: Install and start Apache HTTPD
  hosts: testing
  tasks:
    - name: HTTPD package is present
      apt:
        name: httpd
        state: present
    - name: Correct index.html is present
      copy:
        src: index.html
        dest: /var/www/html/index.html
    - name: httpd is stated
      service: 
        name: httpd
        state: started
        enabled: true
...
