---
#  в одном playbook для разных групп хостов разные play
- name: Play for Install latest apache
  hosts: web
  tasks:
  - name: Install latest apache
    apt:
      name: httpd
      state: latest
- name: Play for Update packages
  hosts: all
  tasks:
  - name: Update packages
    apt:
      name: '*'
      state: latest
...
