---

- name: Install MySQL, Python Installs Packages (pip)
  become: true
  ansible.builtin.apt:
    name:
      - "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - mysql-server
    - pip
  #  - unzip

- name: Make sure pymysql is present
  become: true # needed if the other tasks are not played as root
  ansible.builtin.pip:
    name: pymysql
    state: present

- name: Removes all anonymous user accounts
  community.mysql.mysql_user:
    name: ''
    host_all: true
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock
