# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_DEFAULT_PROVIDER'] = "virtualbox"
$global_box_name="bento/ubuntu-22.04" #"ubuntu/jammy64" 

# Описание параметров ВМ
MACHINES = {
  # Имя DV "pam"
  # :servicenode => {
  #     :box_name => $global_box_name,
  #     :vm_name => "servicenode",
  #     :cpus => 2,
  #     :memory => 8192,
  #     :ip => "192.168.57.11",
  # },
  :nextcloud => {
      :box_name => $global_box_name,
      :vm_name => "nextcloud",
      :cpus => 2,
      :memory => 1024,
      :ip => "192.168.57.12",
  },
  :mysqlrepl => {
      :box_name => $global_box_name,
      :vm_name => "mysqlrepl",
      :cpus => 2,
      :memory => 1024,
      :ip => "192.168.57.13",

  },
  :monitor => {
      :box_name => $global_box_name,
      :vm_name => "monitor",
      :cpus => 2,
      :memory => 1024,
      :ip => "192.168.57.14",

  },
  :elk => {
      :box_name => $global_box_name,
      :vm_name => "elk",
      :cpus => 2,
      :memory => 8192,
      :ip => "192.168.57.15",

  },

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    
    config.vm.define boxname do |box|
   
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      box.vm.network "private_network", ip: boxconfig[:ip]
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end

      if boxconfig[:vm_name] == "elk1"
       box.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/provision.yml"
        ansible.inventory_path = "hosts"
        ansible.host_key_checking = "false"
        ansible.limit = "all"
       end
      end
    end
  end
end
