---
- name: Start mysql
  ansible.builtin.systemd:
    name: mysql
    state: started

- name: Configure mysql source
  ansible.builtin.template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: "Restart mysql-server"

- name: Restart mysql
  ansible.builtin.systemd:
    name: mysql
    state: restarted

- name: Stop mysql replica thread
  community.mysql.mysql_replication:
    mode: stopreplica
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Run RESET MASTER command which will delete all existing binary log files and reset the binary log index file on the primary
  community.mysql.mysql_replication:
    mode: resetprimary
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Restore database
  community.mysql.mysql_db:
    name: all
    state: import
    target: "{{ backup_dir }}/{{ source_hostname }}/mysqldump_{{ source_hostname }}_{{ ansible_date_time.date }}.sql"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Add to Change replication source to replica server
  command: mysql -e "CHANGE REPLICATION SOURCE TO SOURCE_HOST='{{ mysql_source_host_ip }}', SOURCE_USER='{{ mysql_replica_user }}', SOURCE_PASSWORD='{{ mysql_replica_user_password }}', SOURCE_AUTO_POSITION = 1, GET_SOURCE_PUBLIC_KEY = 1;"

- name: Start mysql replica thread
  community.mysql.mysql_replication:
    mode: startreplica
    login_unix_socket: /var/run/mysqld/mysqld.sock
